/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("PatientsListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onThePatientsListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onThePatientsListGenerated.onFilterBar().iCheckFilterField({ property: "patientNo" });
            Then.onThePatientsListGenerated.onFilterBar().iCheckFilterField({ property: "firstName" });
            Then.onThePatientsListGenerated.onFilterBar().iCheckFilterField({ property: "phone" });
            Then.onThePatientsListGenerated.onFilterBar().iCheckFilterField({ property: "bloodGroup" });
            Then.onThePatientsListGenerated.onFilterBar().iCheckFilterField({ property: "isActive" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onThePatientsListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onThePatientsListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onThePatientsListGenerated.onTable(defaultTableId).iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onThePatientsListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"patientNo":{"header":"Patient Number"},"firstName":{"header":"First Name"},"lastName":{"header":"Last Name"},"gender":{"header":"Gender"},"age":{"header":"Age"},"phone":{"header":"Phone"},"isActive":{"header":"Status"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onThePatientsListGenerated.onFilterBar().iExecuteSearch();
            Then.onThePatientsListGenerated.onTable(defaultTableId).iCheckRows();
            When.onThePatientsListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onThePatientsObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});