/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("PatientsObjectPageObjectPage journey");

        opaTest("Navigate to PatientsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onThePatientsListGenerated.onFilterBar().iExecuteSearch();
            Then.onThePatientsListGenerated.onTable().iCheckRows();
            When.onThePatientsListGenerated.onTable().iPressRow(0);

            Then.onThePatientsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onThePatientsObjectPageGenerated.iCheckNumberOfSections(3);
            When.onThePatientsObjectPageGenerated.iPressSectionIconTabFilterButton("FieldGroup::General");
            Then.onThePatientsObjectPageGenerated.iCheckSection({ section: "FieldGroup::General" });
            Then.onThePatientsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "firstName" });
            Then.onThePatientsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "lastName" });
            Then.onThePatientsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "gender" });
            Then.onThePatientsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "genderRemark" });
            Then.onThePatientsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "age" });
            Then.onThePatientsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "bloodGroup" });
            Then.onThePatientsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "isActive" });
            When.onThePatientsObjectPageGenerated.iPressSectionIconTabFilterButton("FieldGroup::Contact");
            Then.onThePatientsObjectPageGenerated.iCheckSection({ section: "FieldGroup::Contact" });
            Then.onThePatientsObjectPageGenerated.onForm({ section: "FieldGroup::Contact" }).iCheckField({ property: "phone" });
            Then.onThePatientsObjectPageGenerated.onForm({ section: "FieldGroup::Contact" }).iCheckField({ property: "email" });
            Then.onThePatientsObjectPageGenerated.onForm({ section: "FieldGroup::Contact" }).iCheckField({ property: "address" });
            Then.onThePatientsObjectPageGenerated.onForm({ section: "FieldGroup::Contact" }).iCheckField({ property: "city" });
            Then.onThePatientsObjectPageGenerated.onForm({ section: "FieldGroup::Contact" }).iCheckField({ property: "state" });
            Then.onThePatientsObjectPageGenerated.onForm({ section: "FieldGroup::Contact" }).iCheckField({ property: "country" });
            Then.onThePatientsObjectPageGenerated.onForm({ section: "FieldGroup::Contact" }).iCheckField({ property: "pincode" });
            When.onThePatientsObjectPageGenerated.iPressSectionIconTabFilterButton("FieldGroup::Emergency");
            Then.onThePatientsObjectPageGenerated.iCheckSection({ section: "FieldGroup::Emergency" });
            Then.onThePatientsObjectPageGenerated.onForm({ section: "FieldGroup::Emergency" }).iCheckField({ property: "emergencyName" });
            Then.onThePatientsObjectPageGenerated.onForm({ section: "FieldGroup::Emergency" }).iCheckField({ property: "emergencyPhone" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});