/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("DoctorsObjectPageObjectPage journey");

        opaTest("Navigate to DoctorsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheDoctorsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheDoctorsListGenerated.onTable().iCheckRows();
            When.onTheDoctorsListGenerated.onTable().iPressRow(0);

            Then.onTheDoctorsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheDoctorsObjectPageGenerated.iCheckNumberOfSections(7);
            When.onTheDoctorsObjectPageGenerated.iPressSectionIconTabFilterButton("FieldGroup::DoctorDetails");
            Then.onTheDoctorsObjectPageGenerated.iCheckSection({ section: "FieldGroup::DoctorDetails" });
            Then.onTheDoctorsObjectPageGenerated.onForm({ section: "FieldGroup::DoctorDetails" }).iCheckField({ property: "First_Name" });
            Then.onTheDoctorsObjectPageGenerated.onForm({ section: "FieldGroup::DoctorDetails" }).iCheckField({ property: "Last_Name" });
            Then.onTheDoctorsObjectPageGenerated.onForm({ section: "FieldGroup::DoctorDetails" }).iCheckField({ property: "Gender" });
            When.onTheDoctorsObjectPageGenerated.iPressSectionIconTabFilterButton("FieldGroup::ProfessionalDetails");
            Then.onTheDoctorsObjectPageGenerated.iCheckSection({ section: "FieldGroup::ProfessionalDetails" });
            Then.onTheDoctorsObjectPageGenerated.onForm({ section: "FieldGroup::ProfessionalDetails" }).iCheckField({ property: "Qualification" });
            Then.onTheDoctorsObjectPageGenerated.onForm({ section: "FieldGroup::ProfessionalDetails" }).iCheckField({ property: "Registration_Number" });
            Then.onTheDoctorsObjectPageGenerated.onForm({ section: "FieldGroup::ProfessionalDetails" }).iCheckField({ property: "Experience" });
            Then.onTheDoctorsObjectPageGenerated.onForm({ section: "FieldGroup::ProfessionalDetails" }).iCheckField({ property: "Joining_Date" });
            Then.onTheDoctorsObjectPageGenerated.onForm({ section: "FieldGroup::ProfessionalDetails" }).iCheckField({ property: "Department_ID" });
            When.onTheDoctorsObjectPageGenerated.iPressSectionIconTabFilterButton("FieldGroup::ContactDetails");
            Then.onTheDoctorsObjectPageGenerated.iCheckSection({ section: "FieldGroup::ContactDetails" });
            Then.onTheDoctorsObjectPageGenerated.onForm({ section: "FieldGroup::ContactDetails" }).iCheckField({ property: "Phone" });
            Then.onTheDoctorsObjectPageGenerated.onForm({ section: "FieldGroup::ContactDetails" }).iCheckField({ property: "Email" });
            Then.onTheDoctorsObjectPageGenerated.onForm({ section: "FieldGroup::ContactDetails" }).iCheckField({ property: "Room_Number" });
            Then.onTheDoctorsObjectPageGenerated.onForm({ section: "FieldGroup::ContactDetails" }).iCheckField({ property: "Consultation_Fee" });
            When.onTheDoctorsObjectPageGenerated.iPressSectionIconTabFilterButton("FieldGroup::StatusDetails");
            Then.onTheDoctorsObjectPageGenerated.iCheckSection({ section: "FieldGroup::StatusDetails" });
            Then.onTheDoctorsObjectPageGenerated.onForm({ section: "FieldGroup::StatusDetails" }).iCheckField({ property: "Doctor_Status" });
            Then.onTheDoctorsObjectPageGenerated.onForm({ section: "FieldGroup::StatusDetails" }).iCheckField({ property: "Availability" });
            When.onTheDoctorsObjectPageGenerated.iPressSectionIconTabFilterButton("Doctor_Specializations::LineItem");
            Then.onTheDoctorsObjectPageGenerated.iCheckSection({ section: "Doctor_Specializations::LineItem" });
            When.onTheDoctorsObjectPageGenerated.iPressSectionIconTabFilterButton("Doctor_Schedule::LineItem");
            Then.onTheDoctorsObjectPageGenerated.iCheckSection({ section: "Doctor_Schedule::LineItem" });
            When.onTheDoctorsObjectPageGenerated.iPressSectionIconTabFilterButton("Doctor_Leaves::LineItem");
            Then.onTheDoctorsObjectPageGenerated.iCheckSection({ section: "Doctor_Leaves::LineItem" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});