/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("DoctorsListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheDoctorsListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheDoctorsListGenerated.onFilterBar().iCheckFilterField({ property: "Doctor_Code" });
            Then.onTheDoctorsListGenerated.onFilterBar().iCheckFilterField({ property: "Full_Name" });
            Then.onTheDoctorsListGenerated.onFilterBar().iCheckFilterField({ property: "Gender" });
            Then.onTheDoctorsListGenerated.onFilterBar().iCheckFilterField({ property: "Department_ID" });
            Then.onTheDoctorsListGenerated.onFilterBar().iCheckFilterField({ property: "Doctor_Status" });
            Then.onTheDoctorsListGenerated.onFilterBar().iCheckFilterField({ property: "Availability" });
            Then.onTheDoctorsListGenerated.onFilterBar().iCheckFilterField({ property: "Qualification" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheDoctorsListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheDoctorsListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheDoctorsListGenerated.onTable(defaultTableId).iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheDoctorsListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"Doctor_Code":{"header":"Doctor ID"},"Full_Name":{"header":"Doctor Name"},"Gender":{"header":"Gender"},"Department_ID":{"header":"Department"},"Joining_Date":{"header":"Joining Date"},"Experience":{"header":"Years of Experience"},"Qualification":{"header":"Qualification"},"Registration_Number":{"header":"Registration Number"},"Phone":{"header":"Phone Number"},"Email":{"header":"Email Address"},"Consultation_Fee":{"header":"Consultation Fee"},"Room_Number":{"header":"Room Number"},"Availability":{"header":"Current Availability"},"Doctor_Status":{"header":"Employment Status"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheDoctorsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheDoctorsListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheDoctorsListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheDoctorsObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});