/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("DoctorSpecializationsObjectPageObjectPage journey");

        opaTest("Navigate to DoctorSpecializationsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheDoctorsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheDoctorsListGenerated.onTable().iCheckRows();
            When.onTheDoctorsListGenerated.onTable().iPressRow(0);

            Then.onTheDoctorsObjectPageGenerated.iSeeThisPage();
            Then.onTheDoctorsObjectPageGenerated.onTable({ property: "Doctor_Specializations" }).iCheckRows();
            When.onTheDoctorsObjectPageGenerated.onTable({ property: "Doctor_Specializations" }).iPressRow(0);

            Then.onTheDoctorSpecializationsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheDoctorSpecializationsObjectPageGenerated.iCheckSection({ section: "FieldGroup::SpecializationDetails" });
            Then.onTheDoctorSpecializationsObjectPageGenerated.onForm({ section: "FieldGroup::SpecializationDetails" }).iCheckField({ property: "Specializations_ID" });
            Then.onTheDoctorSpecializationsObjectPageGenerated.onForm({ section: "FieldGroup::SpecializationDetails" }).iCheckField({ property: "Certification_Date" });
            Then.onTheDoctorSpecializationsObjectPageGenerated.onForm({ section: "FieldGroup::SpecializationDetails" }).iCheckField({ property: "Primary_Specialization" });
            Then.onTheDoctorSpecializationsObjectPageGenerated.onForm({ section: "FieldGroup::SpecializationDetails" }).iCheckField({ property: "Experience_In_Specialization" });
            Then.onTheDoctorSpecializationsObjectPageGenerated.onForm({ section: "FieldGroup::SpecializationDetails" }).iCheckField({ property: "Remarks" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});